import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Providers } from "@/components/providers";
import { headers } from "next/headers";
import { SITE_URL } from "@/lib/site";
import { FREE_FULL_READ } from "@/lib/score-free-tier";
import "./globals.css";

const GDPR_COUNTRIES = new Set([
  // EU member states
  "AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR",
  "GR", "HR", "HU", "IE", "IT", "LT", "LU", "LV", "MT", "NL", "PL",
  "PT", "RO", "SE", "SI", "SK",
  // EEA non-EU
  "IS", "LI", "NO",
  // UK
  "GB",
]);

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || SITE_URL;

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "MixReflect — Know If Your Track Is Ready to Release",
    template: "%s | MixReflect",
  },
  description:
    "Get an instant verdict on whether your track is ready to release — measured against tracks that actually got released — then put it in front of a room of real listeners. Just paste a link. Free to submit.",
  alternates: { canonical: "/" },
  keywords: [
    "music feedback",
    "song score",
    "track score",
    "ai music feedback",
    "get feedback on my music",
    "honest music reviews",
    "pre-release feedback",
    "is my song good",
    "rate my track",
    "music critique",
    "song feedback before release",
  ],
  authors: [{ name: "MixReflect" }],
  creator: "MixReflect",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: "MixReflect",
    title: "MixReflect — Know If Your Track Is Ready to Release",
    description:
      "An instant verdict on whether your track is ready to release — measured against tracks that got released — then a room of real listeners to back it up. Paste a link. Free to submit.",
    // og image generated by src/app/opengraph-image.tsx (file convention)
  },
  twitter: {
    card: "summary_large_image",
    title: "MixReflect — Know If Your Track Is Ready to Release",
    description:
      "An instant verdict on whether your track is ready to release, plus a room of real listeners to back it up. Paste a link. Free to submit.",
    // twitter image generated by src/app/twitter-image.tsx
    creator: "@mixreflect",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: "/apple-touch-icon.png",
  },
};

// JSON-LD structured data for Google and AI crawlers
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      name: "MixReflect",
      url: SITE_URL,
      applicationCategory: "MusicApplication",
      operatingSystem: "Web",
      description: "MixReflect tells you whether your track is ready to release — an instant verdict measured against tracks that actually got released, with the blockers between you and the release bar — then puts it in front of a room of real listeners. The /100 score is the evidence behind the verdict. Just paste a link to your track. Free to submit.",
      offers: [
        {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
          name: "Free",
          description: FREE_FULL_READ
            ? "Your first track's complete report is free — score out of 100, the full written read, all three fixes and the measured waveform. No card needed."
            : "Submit a track and get your instant AI score, verdict and a teaser of the full report.",
        },
        {
          "@type": "Offer",
          price: "6.95",
          priceCurrency: "USD",
          name: "Unlock",
          description: "One-time unlock of a track's full report — the complete breakdown plus every listener reaction. Yours forever.",
        },
        {
          "@type": "Offer",
          price: "19.95",
          priceCurrency: "USD",
          name: "Unlimited",
          description: "Every track you submit is auto-unlocked. Unlimited full reports, billed monthly.",
        },
      ],
    },
    {
      "@type": "Organization",
      name: "MixReflect",
      url: SITE_URL,
      logo: `${SITE_URL}/logo.png`,
      description: "MixReflect gives artists an instant, measured verdict on whether a track is ready to release, then puts it in front of a room of real listeners. Free to submit.",
      sameAs: ["https://twitter.com/mixreflect"],
      contactPoint: {
        "@type": "ContactPoint",
        contactType: "customer support",
        url: `${SITE_URL}/support`,
      },
    },
    {
      "@type": "WebSite",
      name: "MixReflect",
      url: SITE_URL,
      description: "Know if your track is ready to release — an instant, measured verdict plus a room of real listeners, before you put it out.",
      potentialAction: {
        "@type": "SearchAction",
        target: `${SITE_URL}/feedback/{search_term_string}`,
        "query-input": "required name=search_term_string",
      },
    },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const country = headersList.get("x-vercel-ip-country") ?? "";
  const requiresConsent = GDPR_COUNTRIES.has(country);

  return (
    <html lang="en" data-theme="light" style={{ colorScheme: "light" }}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${plusJakarta.variable} antialiased`}
      >
        <Providers requiresConsent={requiresConsent}>
          {children}
        </Providers>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
